server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  
router:
  enabled: true
  port: 8000
  
context_expansion:
  enabled: true
  port: 8001
  chunk_size: 2000
  chunk_overlap: 200
  max_context_files: 10
  
logging:
  level: "INFO"
  format: "structured"
  file: "logs/system.log"
  
vector_store:
  type: "faiss"  # or "chroma"
  persist_directory: "./vector_stores"
  auto_refresh: true
